accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views


app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic.
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry.
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    # Page for generating an image
    path('generation/', views.generation, name='generation'),
    # Page that displays the generated images
    path('gallery/', views.gallery, name='gallery'),
    # Page that displays the user image generation history
    path('user_history/', views.user_history, name='user_history'),
    # Page to show the about us content
    path('about/', views.about, name='about'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a simple string representing the entry."""
        return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('learning_logs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)








# Addition of imageForge Views

def generation(request):
    """Show generation page."""
    return render(request, 'learning_logs/generation.html')

def gallery(request):
    """Show gallery page."""
    return render(request, 'learning_logs/gallery.html')

def user_history(request):
    """Show user history page."""
    return render(request, 'learning_logs/user_history.html')

def about(request):
    """Show the about page."""
    return render(request, 'learning_logs/about.html')

learning_logs/templates/learning_logs/about.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>About Us</h1>
{% endblock page_header %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-3" style="height: 30vh">
        <div class="card-body d-flex align-items-center justify-content-center">
          <div
            class="border border-secondary rounded p-3 text-center"
            style="width: 100%; height: 100%"
          >
            <!-- Content for the first box goes here -->
          </div>
        </div>
      </div>
      <div class="mt-4"></div>
      <!-- 20% gap between boxes -->
      <div class="card" style="height: 30vh">
        <div class="card-body d-flex align-items-center justify-content-center">
          <div
            class="border border-secondary rounded p-3 text-center"
            style="width: 100%; height: 100%"
          >
            <!-- Content for the second box goes here -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>imageForge</title>

    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    {% load static %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    />
    <!-- Add jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Add the Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
          imageForge</a
        >

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul
            class="navbar-nav me-auto mb-2 mb-md-0 navbar-nav d-flex justify-content-evenly w-100"
          >
            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                Topics</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:generation' %}">
                Generation</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:gallery' %}">
                Gallery</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:user_history' %}">
                User History</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:about' %}">
                About</a
              >
            </li>
          </ul>
          <!-- End of links on left side of navbar -->

          <!-- Account-related links -->
          <ul class="navbar-nav ms-auto mb-2 mb-md-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}. </span>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                Register</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}"> Log in</a>
            </li>
            {% endif %}
          </ul>
          <!-- End of account-related links -->

          {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button name="submit" class="btn btn-outline-secondary btn-sm">
              Log out
            </button>
          </form>
          {% endif %}
        </div>
        <!-- Closes collapsible parts of navbar -->
      </div>
      <!-- Closes navbar's container -->
    </nav>
    <!-- End of navbar -->

    <main class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>

      <div>{% block content %}{% endblock content %}</div>
    </main>
    <footer class="bg-dark text-white py-3 fixed-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div class="d-flex justify-content-start">
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-github-square social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-linkedin social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-twitter-square social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-instagram social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
            </div>
          </div>
          <div class="col-md-6">
            <div class="d-flex justify-content-end">
              <a href="#" class="btn btn-primary subscribe-btn">Subscribe</a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Edit entry:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/gallery.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>Gallery</h1>
{% endblock page_header %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <p>This is the gallery page</p>
  </body>
</html>

{% endblock content %}

learning_logs/templates/learning_logs/generation.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>Generation</h1>
{% endblock page_header %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <p>This is taking the place of the image generation command</p>
  </body>
</html>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<div class="p-3 mb-4 bg-light border rounded-3">
  <div class="container-fluid py-4">
    <h1 class="display-3">Welcome to imageForge!</h1>

    {% endblock page_header %}{% block content %}

    <p class="lead">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam malesuada
      massa nec orci volutpat, non luctus lacus efficitur. Ut vitae nunc velit.
      Nam vulputate pellentesque leo, vel pharetra neque eleifend at. Mauris ac
      dolor ut metus convallis luctus. Nunc finibus orci ipsum, id bibendum
      lacus posuere in. Vestibulum at justo felis. Fusce eget enim nec est
      aliquam dignissim a a ligula. Integer id ipsum turpis.
    </p>

    <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}"
      >Register &raquo;</a
    >
  </div>
</div>

{# This is the GENERATION button #}

<div
  class="d-flex justify-content-center align-items-center"
  style="height: 20vh"
>
  <button
    id="generateButton"
    type="submit"
    class="btn btn-success btn-lg mt-1"
    data-bs-toggle="modal"
    data-bs-target="#myModal"
  >
    GENERATE
  </button>
</div>

{# Addition of the Modal pop-up box template #}

<div
  class="modal fade"
  id="myModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered" style="margin-top: 0vh">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h5 class="modal-title mx-auto" id="exampleModalLabel">
          Generated Image Prompt:
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body text-center">
        <p>Insertion of the image generation prompt</p>
      </div>
      <div class="modal-footer justify-content-center">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Close
        </button>
        <button type="button" class="btn btn-primary" id="createPromptButton">
          Create New Prompt
        </button>
        <button type="button" class="btn btn-success" id="sendPromptButton">
          Send Prompt to DALL•E 2
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Addition of a script tag to run the query generation program when the 'GENERATION' button is clicked -->

<script>
  $(document).ready(function () {
    $("#generateButton").click(function () {
      // Execute your script here
      alert("GENERATION button clicked!"); // Example script, replace with your own code
    });
  });
</script>

<!-- Addition of a script tag to run the query generation program when the 'Create
New Prompt' button is clicked -->

<script>
  $(document).ready(function () {
    $("#createPromptButton").click(function () {
      // Execute your script here
      alert("Prompt button clicked!"); // Example script, replace with your own code
    });
  });
</script>

<!-- Addition of a script tag to run the query the DALL•E 2 API when the 'Send Prompt to DALL•E 2' button is clicked -->

<script>
  $(document).ready(function () {
    $("#sendPromptButton").click(function () {
      // Execute your script here
      alert("Generation button clicked!"); // Example script, replace with your own code
    });
  });
</script>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name='submit'>Add entry</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Add a new topic:</p>

  <form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Add topic</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h1>{{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="card mb-3">
      <!-- Card header with timestamp and edit link -->
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
          edit entry</a></small>
      </h4>
      <!-- Card body with entry text -->
      <div class="card-body">{{ entry.text|linebreaks }}</div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

  <ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in topics %}
      <li class="list-group-item border-0">
        <a href="{% url 'learning_logs:topic' topic.id %}">
          {{ topic.text }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">No topics have been added yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}

learning_logs/templates/learning_logs/user_history.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>User History</h1>
{% endblock page_header %} {% block content %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <p>This is the user history page</p>
  </body>
</html>

{% endblock content %}